param ($old_version_folder, $new_version_folder, $stable_version, $beta_version, $token, $html_path);

if ([string]::IsNullOrEmpty($old_version_folder)) {
    Write-Host "old_version_folder was not provided! Exiting...";
    exit;
}
if ([string]::IsNullOrEmpty($new_version_folder)) {
    Write-Host "new_version_folder was not provided! Exiting...";
    exit;
}
if ([string]::IsNullOrEmpty($stable_version)) {
    Write-Host "stable_version was not provided! Exiting...";
    exit;
}
if ([string]::IsNullOrEmpty($beta_version)) {
    Write-Host "beta_version was not provided! Exiting...";
    exit;
}
if ([string]::IsNullOrEmpty($token)) {
    Write-Host "token was not provided! Exiting...";
    exit;
}

$stable_version=$stable_version.substring(1);
$beta_version=$beta_version.substring(1);
dotnet run --project PackageDownloader -- -s $stable_version -b $beta_version -n Bannerlord.ReferenceAssemblies -t $PWD -f https://nuget.pkg.github.com/BUTR/index.json -u BUTR -p $token

Write-Output "Started...";
$mappings = @{};
$mappings.Add('bannerlord.referenceassemblies.core.earlyaccess', 'Core');
$mappings.Add('bannerlord.referenceassemblies.native.earlyaccess', 'Native');
$mappings.Add('bannerlord.referenceassemblies.sandbox.earlyaccess', 'SandBox');
$mappings.Add('bannerlord.referenceassemblies.storymode.earlyaccess', 'StoryMode');
$mappings.Add('bannerlord.referenceassemblies.custombattle.earlyaccess', 'CustomBattle');
$mappings.Add('bannerlord.referenceassemblies.birthanddeath.earlyaccess', 'BirthAndDeath');

$excludes = @(
    '*AutoGenerated*',
    '*BattlEye*');

$old  = [IO.Path]::Combine($(Get-Location), "old" );
$new  = [IO.Path]::Combine($(Get-Location), "new" );
$diff = [IO.Path]::Combine($(Get-Location), "diff");
$html = [IO.Path]::Combine($(Get-Location), "html");
$json = [IO.Path]::Combine($(Get-Location), "json");
New-Item -ItemType directory -Path $diff -Force | Out-Null;
New-Item -ItemType directory -Path $html -Force | Out-Null;
New-Item -ItemType directory -Path $json -Force | Out-Null;

$old_folders = Get-ChildItem -Path $old_version_folder | Sort-Object -desc;
$new_folders = Get-ChildItem -Path $new_version_folder | Sort-Object -desc;

foreach ($key in $mappings.Keys) {
    $mapping = $mappings[$key];
    Write-Output "Handling $mapping...";
    
    $old_path = [IO.Path]::Combine($old_version_folder, $key);
    $new_path = [IO.Path]::Combine($new_version_folder, $key);
    if (!(Test-Path "$old_path")) { continue; }
    if (!(Test-Path "$new_path")) { continue; }

    $contains = $false;
    foreach ($of in $old_folders) { if ([IO.Path]::GetFileName($of) -eq $key) { $contains = $true; } }
    foreach ($nf in $new_folders) { if ([IO.Path]::GetFileName($nf) -eq $key) { $contains = $true; } }
    if (!$contains) { continue; }

    $old_files = Get-ChildItem -Path $($old_path + '/*.dll') -Recurse -Exclude $excludes | Sort-Object -desc;
    $new_files = Get-ChildItem -Path $($new_path + '/*.dll') -Recurse -Exclude $excludes | Sort-Object -desc;


    # generate source code based on the Public API
    Write-Output "Generating Stable source code...";
    foreach ($file in $old_files) {
        $fileWE = [IO.Path]::GetFileNameWithoutExtension($file);
        $old_folder  = [IO.Path]::Combine($old, $mapping, $fileWE);
        New-Item -ItemType directory -Path $old_folder -Force | Out-Null;

        Write-Output "Generating for $fileWE...";
        dotnet ilspycmd "$($file.FullName)" --project --outputdir "$old_folder" | Out-Null;
    }
    Write-Output  "Generating Beta source code...";
    foreach ($file in $new_files) {
        $fileWE = [IO.Path]::GetFileNameWithoutExtension($file);
        $new_folder  = [IO.Path]::Combine($new, $mapping, $fileWE);
        New-Item -ItemType directory -Path $new_folder -Force | Out-Null;

        Write-Output "Generating for $fileWE...";
        dotnet ilspycmd "$($file.FullName)" --project --outputdir "$new_folder" | Out-Null;
    }


    # delete csproj files
    Write-Output  "Deleting csproj's...";
    Get-ChildItem -Path $($old + '/**/*.csproj') -Recurse -ErrorAction SilentlyContinue | foreach { Remove-Item -Path $_.FullName };
    Get-ChildItem -Path $($new + '/**/*.csproj') -Recurse -ErrorAction SilentlyContinue | foreach { Remove-Item -Path $_.FullName };
    
    # removing usings from diff
    Write-Output  "Removing using's...";
    Get-ChildItem -Path $($old + '/**/*.cs') -Recurse -ErrorAction SilentlyContinue | foreach {
        $content = [System.IO.File]::ReadAllText("$_");
        $idx = $content.IndexOf("namespace");
        if ($idx -ne -1) {
            [System.IO.File]::WriteAllText(
                "$_",
                $content.Substring($idx)
            );
        }
    };
    Get-ChildItem -Path $($new + '/**/*.cs') -Recurse -ErrorAction SilentlyContinue | foreach {
        $content = [System.IO.File]::ReadAllText("$_");
        $idx = $content.IndexOf("namespace");
        if ($idx -ne -1) {
            [System.IO.File]::WriteAllText(
                "$_",
                $content.Substring($idx)
            );
        }
    };
    
    # generate the diff, md and html files
    Write-Output "Generating diff's...";
    foreach ($file in $old_files) {
        $fileWE = [IO.Path]::GetFileNameWithoutExtension($file);
        $old_folder = [IO.Path]::Combine($old, $mapping, $fileWE);
        $new_folder = [IO.Path]::Combine($new, $mapping, $fileWE);
        if (!(Test-Path "$old_folder")) { continue; }
        if (!(Test-Path "$new_folder")) { continue; }

        $diff_folder = [IO.Path]::Combine($diff, $mapping);
        $diff_file = [IO.Path]::Combine($diff_folder, $fileWE + '.diff');
        New-Item -ItemType directory -Path "$diff_folder" -Force | Out-Null;

        $html_folder = [IO.Path]::Combine($html, $mapping);
        $html_file = [IO.Path]::Combine($html_folder, $fileWE + '.html');
        New-Item -ItemType directory -Path "$html_folder" -Force | Out-Null;
        
        $json_folder = [IO.Path]::Combine($json, $mapping);
        $json_file = [IO.Path]::Combine($json_folder, $fileWE + '.json');
        New-Item -ItemType directory -Path "$json_folder" -Force | Out-Null;

        Write-Output "Generating diff as $diff_file...";
        git diff --no-index -u --relative "$old_folder" "$new_folder" --output "$diff_file";
        [System.IO.File]::WriteAllText("$diff_file", [System.IO.File]::ReadAllText("$diff_file").Replace("a/old/","").Replace("a/new/","").Replace("b/old/","").Replace("b/new/",""));

        if (![string]::IsNullOrEmpty($(Get-Content $diff_file))) {
            Write-Output "Generating html as $html_file...";
            diff2html -F "$html_file" -f html -i file -- "$diff_file";
            Write-Output "Generating json as $json_file...";
            diff2html -F "$json_file" -f json -i file -- "$diff_file";
        }
    }
    foreach ($file in $new_files) {
        $fileWE = [IO.Path]::GetFileNameWithoutExtension($file);
        $old_folder = [IO.Path]::Combine($old, $mapping, $fileWE);
        $new_folder = [IO.Path]::Combine($new, $mapping, $fileWE);
        if (!(Test-Path "$old_folder")) { continue; }
        if (!(Test-Path "$new_folder")) { continue; }

        $diff_folder = [IO.Path]::Combine($diff, $mapping);
        $diff_file = [IO.Path]::Combine($diff_folder, $fileWE + '.diff');
        New-Item -ItemType directory -Path "$diff_folder" -Force | Out-Null;

        $html_folder = [IO.Path]::Combine($html, $mapping);
        $html_file = [IO.Path]::Combine($html_folder, $fileWE + '.html');
        New-Item -ItemType directory -Path "$html_folder" -Force | Out-Null;

        $json_folder = [IO.Path]::Combine($json, $mapping);
        $json_file = [IO.Path]::Combine($json_folder, $fileWE + '.json');
        New-Item -ItemType directory -Path "$json_folder" -Force | Out-Null;

        Write-Output "Generating diff as $diff_file...";
        git diff --no-index -u --relative "$old_folder" "$new_folder" --output "$diff_file";
        [System.IO.File]::WriteAllText("$diff_file", [System.IO.File]::ReadAllText("$diff_file").Replace("a/old/","").Replace("a/new/","").Replace("b/old/","").Replace("b/new/",""));
        
        if (![string]::IsNullOrEmpty($(Get-Content $diff_file))) {
            Write-Output "Generating html as $html_file...";
            diff2html -F "$html_file" -f html -i file -- "$diff_file";
            Write-Output "Generating json as $json_file...";
            diff2html -F "$json_file" -f json -i file -- "$diff_file";
        }
    }
}

tree ./html -H $html_path  --noreport --charset utf-8 -o ./html/index.html;
