name: Build ReferenceAssemblies-Diff Docker Image 

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/referenceassemblies-diff-docker.yml'
      - 'referenceassemblies-diff/**'
  workflow_dispatch:

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  generate:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: BUTR
        password: ${{ secrets.TOKEN_GPR }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./referenceassemblies-diff
        file: ./referenceassemblies-diff/Dockerfile
        platforms: linux/amd64
        #platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/butr/referenceassemblies-diff:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}