name: Publish ReferenceAssemblies-Diff on Game Update

on:
  repository_dispatch:
    types: [game_version_update]
  workflow_dispatch:

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  generate:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - uses: kohlerdominik/docker-run-action@v1
      with:
        image: ghcr.io/butr/referenceassemblies-diff:latest
        volumes: |
          ${{ github.workspace }}/html:/html
          ${{ github.workspace }}/json:/json
          ${{ github.workspace }}/diff:/diff
        environment: |
          OLD_VERSION_FOLDER=./Stable
          NEW_VERSION_FOLDER=./Beta
          STABLE_VERSION=${{vars.GAME_VERSION_STABLE}}
          BETA_VERSION=${{vars.GAME_VERSION_BETA}}
          TOKEN=${{secrets.GITHUB_TOKEN}}
          HTML_PATH=.
        run: |
          pwsh ./generate-diffs.ps1 -old_version_folder $OLD_VERSION_FOLDER -new_version_folder $NEW_VERSION_FOLDER -stable_version $STABLE_VERSION -beta_version $BETA_VERSION -token $TOKEN -html_path $HTML_PATH

    - name: Publish Diff
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "${{ github.workspace }}/diff/"
        remote: "/deploy/referenceassembliesdiffer/diff/${{secrets.SYNCED_GAME_STABLE_VERSION}}-${{secrets.SYNCED_GAME_BETA_VERSION}}/"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey : ${{ secrets.KEY }}
        concurrency: 10
        verbose: false
        rmRemote: true

    - name: Publish Html
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "${{ github.workspace }}/html/"
        remote: "/deploy/referenceassembliesdiffer/html/${{secrets.SYNCED_GAME_STABLE_VERSION}}-${{secrets.SYNCED_GAME_BETA_VERSION}}/"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey : ${{ secrets.KEY }}
        concurrency: 10
        verbose: false
        rmRemote: true
        
    - name: Publish Html
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "${{ github.workspace }}/json/"
        remote: "/deploy/referenceassembliesdiffer/json/${{secrets.SYNCED_GAME_STABLE_VERSION}}-${{secrets.SYNCED_GAME_BETA_VERSION}}/"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey : ${{ secrets.KEY }}
        concurrency: 10
        verbose: false
        rmRemote: true
